import type { Metadata } from "next";
import { Markazi_Text } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import { ThemeProviderWrapper } from "@/providers/themeProvider";
import { Navbar } from "@/components/ui/navbar";

const markazi = Markazi_Text({
  subsets: ['arabic'],
  variable: '--font-markazi',
  display: 'swap'
})

const potk = localFont({
  src: './fonts/Potk.woff',
  variable: '--font-potk',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body
        className={`${markazi.variable} ${potk.variable} antialiased bg-background`}
      >
        <ThemeProviderWrapper>
          <Navbar />
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
